// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3);
}

export function AddCategory(arg1, arg2) {
  return window['go']['main']['App']['AddCategory'](arg1, arg2);
}

export function AddUser(arg1) {
  return window['go']['main']['App']['AddUser'](arg1);
}

export function DeleteInvestment(arg1) {
  return window['go']['main']['App']['DeleteInvestment'](arg1);
}

export function FetchAccountDetails(arg1) {
  return window['go']['main']['App']['FetchAccountDetails'](arg1);
}

export function FetchCategories(arg1) {
  return window['go']['main']['App']['FetchCategories'](arg1);
}

export function UpdateCash(arg1, arg2) {
  return window['go']['main']['App']['UpdateCash'](arg1, arg2);
}

export function UpdateInvestment(arg1) {
  return window['go']['main']['App']['UpdateInvestment'](arg1);
}
