// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:number,arg2:string,arg3:string):Promise<number>;

export function AddCategory(arg1:number,arg2:string):Promise<void>;

export function AddUser(arg1:string):Promise<number>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteInvestment(arg1:number):Promise<void>;

export function FetchAccountDetails(arg1:number):Promise<Array<main.account>>;

export function FetchCategories(arg1:number):Promise<main.categories>;

export function UpdateCash(arg1:number,arg2:number):Promise<void>;

export function UpdateInvestment(arg1:Array<main.investment>):Promise<void>;
