// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLatestAsset():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function SaveAsset(arg1:number):Promise<void>;
