// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLatestAsset() {
  return window['go']['main']['App']['FetchLatestAsset']();
}

export function SaveAsset(arg1) {
  return window['go']['main']['App']['SaveAsset'](arg1);
}
