// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {app} from '../models';

export function AddAccount(arg1:number,arg2:string,arg3:string):Promise<number>;

export function AddCategory(arg1:number,arg2:string):Promise<void>;

export function AddUser(arg1:string):Promise<number>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteInvestment(arg1:number):Promise<void>;

export function FetchAccountDetails(arg1:number):Promise<Array<db.Account>>;

export function FetchCategories(arg1:number):Promise<db.Categories>;

export function GetExchangeRates(arg1:string,arg2:Array<string>):Promise<app.ExchangeRates>;

export function SaveInvestmentStatistics(arg1:Array<app.InvestmentTrimmed>):Promise<void>;

export function UpdateCash(arg1:number,arg2:number,arg3:string):Promise<void>;

export function UpdateInvestment(arg1:Array<db.Investment>):Promise<void>;
